import { expect, test, type Page } from '@playwright/test';

async function mockPreload(page:Page){await page.addInitScript(()=>{const rows:any[]=[];(window as any).damplanner={list:async()=>rows,settings:async()=>({timezone:'Europe/Paris',googleDefaultCalendarId:'primary',googleAvailabilityCalendarIds:['primary'],twitchClientId:'test',availabilityLocal:true,availabilityGoogle:false,availabilityTwitch:false,onboardingDone:true,googleConfigured:true,googleConnected:true,twitchConfigured:true,twitchConnected:true}),preview:async(input:any)=>{const conflict=rows.find(x=>x.event.startAtUtc<input.endAtUtc&&x.event.endAtUtc>input.startAtUtc);return{event:input,availability:{status:conflict?'CONFLICT':'AVAILABLE',hash:'accepted',errors:[],conflicts:conflict?[{...conflict.event,source:'LOCAL'}]:[]}}},save:async(input:any,id?:string,hash?:string)=>{const event={...input,id:id??crypto.randomUUID(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),deletedAt:null,conflictOverrideHash:hash??null,conflictOverrideAt:hash?new Date().toISOString():null};const i=rows.findIndex(x=>x.event.id===id);const row={event,google:input.syncGoogle?{status:'SYNCED'}:undefined,twitch:input.syncTwitch?{status:'SYNCED'}:undefined};if(i<0)rows.push(row);else rows[i]=row;return event},remove:async(id:string)=>{const i=rows.findIndex(x=>x.event.id===id);if(i>=0)rows.splice(i,1)},retry:async()=>{},categories:async()=>[{id:'1',name:'Just Chatting',boxArtUrl:''}],updateSettings:async()=>{},importGoogle:async()=>true,connectGoogle:async()=>{},disconnectGoogle:async()=>{},calendars:async()=>[],beginTwitch:async()=>({}),completeTwitch:async()=>{},disconnectTwitch:async()=>{},openExternal:async()=>{}}})}
async function fill(page:Page,title:string,kind='LIVE'){await page.getByText('+ Nouvel événement').first().click();await page.getByLabel('Type').selectOption(kind);await page.getByLabel('Titre',{exact:true}).fill(title);await page.getByLabel('Date').fill('2026-09-03');await page.getByLabel('Début').fill('20:00');await page.getByLabel('Fin').fill('22:00')}

test.beforeEach(async({page})=>{await mockPreload(page);await page.goto('/')});
test('création LIVE Google+Twitch, modification et suppression',async({page})=>{await fill(page,'Soirée Twitch');await page.getByText('Google Calendar').click();await page.getByText('Twitch',{exact:true}).click();await page.getByLabel('Titre public Twitch').fill('Live public');await page.getByLabel('Catégorie Twitch').fill('Just');await page.getByText('Just Chatting').click();await page.getByText('Prévisualiser').click();await expect(page.getByText('Soirée Twitch')).toBeVisible();await page.getByText('Modifier').click();await page.getByLabel('Titre',{exact:true}).fill('Soirée modifiée');await page.getByText('Prévisualiser').click();await expect(page.getByText('Soirée modifiée')).toBeVisible();page.once('dialog',d=>d.accept());await page.getByText('Supprimer').click();await expect(page.getByText('Soirée modifiée')).toHaveCount(0);});
test('PERSONAL Google only',async({page})=>{await fill(page,'Rendez-vous','PERSONAL');await page.getByText('Google Calendar').click();await page.getByText('Prévisualiser').click();await expect(page.getByText('Rendez-vous')).toBeVisible();await expect(page.getByText('Google: SYNCED')).toBeVisible()});
test('deux événements simultanés sont conservés après confirmation',async({page})=>{await fill(page,'Premier');await page.getByText('Prévisualiser').click();await fill(page,'Second');await page.getByText('Prévisualiser').click();await expect(page.getByText('Chevauchement détecté')).toBeVisible();await page.getByText('Valider quand même').click();await expect(page.getByText('Premier')).toBeVisible();await expect(page.getByText('Second')).toBeVisible();await expect(page.getByText('Chevauchement accepté')).toBeVisible()});
