import type { PlannerEvent } from '../domain/models.js';
import { AuthenticatedFetch, jsonOrError, type OAuthTokens } from '../oauth/authenticated-fetch.js';
import type { SecureTokenStore } from '../oauth/token-store.js';
import { AmbiguousCreateError, ReauthRequiredError, type RemoteSlot, type TwitchProvider } from './contracts.js';

interface TwitchIdentity { id: string; display_name: string; login: string }
interface DeviceState { deviceCode:string; userCode:string; verificationUri:string; expiresAt:number; interval:number }
interface HelixSegment { id:string; start_time:string; end_time:string; title:string; category?:{id:string;name:string} }

export class TwitchScheduleProvider extends AuthenticatedFetch implements TwitchProvider {
  private broadcasterId=''; private nextRequestAt=0;
  constructor(store:SecureTokenStore,private readonly clientId:()=>Promise<string>){super(store,'twitch-tokens')}
  async configured(){return Boolean(await this.clientId())} async connected(){try{await this.readTokens();return true}catch{return false}} async disconnect(){await this.clearTokens();this.broadcasterId=''}
  async beginDeviceFlow():Promise<DeviceState>{const clientId=await this.clientId();if(!clientId)throw new Error('Twitch Client ID manquant');const r=await fetch('https://id.twitch.tv/oauth2/device',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:clientId,scopes:'channel:manage:schedule'})});const d=await jsonOrError<{device_code:string;user_code:string;verification_uri:string;expires_in:number;interval:number}>(r);return{deviceCode:d.device_code,userCode:d.user_code,verificationUri:d.verification_uri,expiresAt:Date.now()+d.expires_in*1000,interval:d.interval}}
  async completeDeviceFlow(state:DeviceState):Promise<TwitchIdentity>{const clientId=await this.clientId();while(Date.now()<state.expiresAt){await new Promise(r=>setTimeout(r,state.interval*1000));const r=await fetch('https://id.twitch.tv/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:clientId,device_code:state.deviceCode,grant_type:'urn:ietf:params:oauth:grant-type:device_code'})});if(r.ok){const t=await r.json()as{access_token:string;refresh_token:string;expires_in:number};await this.writeTokens({accessToken:t.access_token,refreshToken:t.refresh_token,expiresAt:Date.now()+t.expires_in*1000});return this.identity()}const e=await r.json()as{message?:string};if(!/pending|slow/i.test(e.message??''))throw new Error(e.message??'Échec Device Code Twitch')}throw new Error('Code Twitch expiré')}
  protected async refresh(value:OAuthTokens){const clientId=await this.clientId();if(!clientId||!value.refreshToken){await this.clearTokens();throw new ReauthRequiredError('Reconnexion Twitch requise')}const r=await fetch('https://id.twitch.tv/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'refresh_token',refresh_token:value.refreshToken,client_id:clientId})});if(!r.ok){await this.clearTokens();throw new ReauthRequiredError('Jeton Twitch révoqué')}const t=await r.json()as{access_token:string;refresh_token?:string;expires_in:number};const next={accessToken:t.access_token,refreshToken:t.refresh_token??value.refreshToken,expiresAt:Date.now()+t.expires_in*1000};await this.writeTokens(next);return next}
  private async helix<T>(path:string,init:RequestInit={},rateRetry=true):Promise<T>{const wait=this.nextRequestAt-Date.now();if(wait>0)await new Promise(r=>setTimeout(r,wait));const clientId=await this.clientId();const response=await this.authorized(`https://api.twitch.tv/helix${path}`,{...init,headers:{...Object.fromEntries(new Headers(init.headers).entries()),'Client-Id':clientId}});const reset=Number(response.headers.get('ratelimit-reset'))*1000,remaining=Number(response.headers.get('ratelimit-remaining'));if(remaining===0)this.nextRequestAt=reset;if(response.status===429&&rateRetry){this.nextRequestAt=Math.max(reset,Date.now()+1000);return this.helix<T>(path,init,false)}return jsonOrError<T>(response)}
  async identity(){const data=await this.helix<{data:TwitchIdentity[]}>('/users');const user=data.data[0];if(!user)throw new ReauthRequiredError('Compte Twitch introuvable');this.broadcasterId=user.id;return user}
  private async broadcaster(){if(!this.broadcasterId)await this.identity();return this.broadcasterId}
  async searchCategories(query:string){if(query.trim().length<2)return[];const d=await this.helix<{data:{id:string;name:string;box_art_url:string}[]}>(`/search/categories?query=${encodeURIComponent(query)}&first=20`);return d.data.map(x=>({id:x.id,name:x.name,boxArtUrl:x.box_art_url.replace('{width}','52').replace('{height}','72')}))}
  async schedule(start:string,end:string){const id=await this.broadcaster(),all:HelixSegment[]=[];let cursor='';do{let data:{data:{segments:HelixSegment[]};pagination:{cursor?:string}};try{data=await this.helix<{data:{segments:HelixSegment[]};pagination:{cursor?:string}}>(`/schedule?broadcaster_id=${id}&start_time=${encodeURIComponent(start)}&first=25${cursor?`&after=${encodeURIComponent(cursor)}`:''}`)}catch(error){if(error instanceof Error&&/^API distante 404:/.test(error.message))return[];throw error}all.push(...(data.data.segments??[]));cursor=data.pagination.cursor??''}while(cursor);return all.filter(x=>x.start_time<end&&x.end_time>start).map(this.slot)}
  private slot(x:HelixSegment):RemoteSlot{return{id:x.id,startAtUtc:x.start_time,endAtUtc:x.end_time,title:x.title,categoryId:x.category?.id}}
  private body(e:PlannerEvent){return{start_time:e.startAtUtc,timezone:e.timezone,duration:Math.round((Date.parse(e.endAtUtc)-Date.parse(e.startAtUtc))/60000),category_id:e.twitchCategoryId!,title:e.twitchTitle!,is_recurring:false}}
  async create(e:PlannerEvent){try{const d=await this.helix<{data:{segments:HelixSegment[]} }>(`/schedule/segment?broadcaster_id=${await this.broadcaster()}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(this.body(e))});const id=d.data.segments[0]?.id;if(!id)throw new Error('Twitch n’a retourné aucun segment');return id}catch(error){if(error instanceof TypeError||error instanceof DOMException||error instanceof Error&&/API distante 5\d\d/.test(error.message))throw new AmbiguousCreateError();throw error}}
  async update(id:string,e:PlannerEvent){const body=this.body(e);await this.helix(`/schedule/segment?broadcaster_id=${await this.broadcaster()}&id=${encodeURIComponent(id)}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})}
  async delete(id:string){await this.helix(`/schedule/segment?broadcaster_id=${await this.broadcaster()}&id=${encodeURIComponent(id)}`,{method:'DELETE'})}
}
